torch version ::: 1.9.0+cu111
device        ::: cuda:0
Dataset
DataLoader
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Model
loss
opt
tr_loss_avg ::: 1.9029886722564697, tr_acc_avg ::: 0.5726174645390071
val_loss_avg ::: 1.5304794311523438, val_acc_avg ::: 0.7791015625
tr_loss_avg ::: 1.3198031187057495, tr_acc_avg ::: 0.7917331560283688
val_loss_avg ::: 1.117138385772705, val_acc_avg ::: 0.81884765625
tr_loss_avg ::: 1.0138049125671387, tr_acc_avg ::: 0.8216976950354611
val_loss_avg ::: 0.8962224125862122, val_acc_avg ::: 0.83662109375
tr_loss_avg ::: 0.8383523225784302, tr_acc_avg ::: 0.83828125
val_loss_avg ::: 0.7452653050422668, val_acc_avg ::: 0.85458984375
tr_loss_avg ::: 0.7272441387176514, tr_acc_avg ::: 0.8506316489361702
val_loss_avg ::: 0.6605652570724487, val_acc_avg ::: 0.86552734375
tr_loss_avg ::: 0.6504939794540405, tr_acc_avg ::: 0.8593971631205675
val_loss_avg ::: 0.5912683010101318, val_acc_avg ::: 0.87509765625
tr_loss_avg ::: 0.5946396589279175, tr_acc_avg ::: 0.866904920212766
val_loss_avg ::: 0.5437262654304504, val_acc_avg ::: 0.87900390625
tr_loss_avg ::: 0.5523313879966736, tr_acc_avg ::: 0.8721631205673759
val_loss_avg ::: 0.5094490051269531, val_acc_avg ::: 0.8828125
tr_loss_avg ::: 0.5178715586662292, tr_acc_avg ::: 0.8772772606382979
val_loss_avg ::: 0.4796501100063324, val_acc_avg ::: 0.8892578125
tr_loss_avg ::: 0.49029281735420227, tr_acc_avg ::: 0.8813164893617021
val_loss_avg ::: 0.4567280411720276, val_acc_avg ::: 0.89287109375
training finishes
Traceback (most recent call last):
  File "simple_training.py", line 123, in <module>
    ax[div][mod].subplot(5, 5, i+1)
AttributeError: 'AxesSubplot' object has no attribute 'subplot'